export enum LogType {
  ABORT = 'ABORT',
  ALERT = 'ALERT',
  ERROR = 'ERROR',
  FAIL = 'FAILURE',
  LISTEN = 'LISTEN',
  INFO = 'INFO',
  RECEIVED = 'RECEIVED',
  SENT = 'SENT',
  STARTED = 'START',
  STOPPED = 'STOPPED',
  SUCCESS = 'SUCCESS',
}
